name: Cancel workflows
on:
  workflow_run:
    workflows:
      - "Check Apps Version"
      - "Build slim packages"
      - "Check Rebar Dependencies"
      - "Elvis Linter"
      - "Compatibility Test Suite"
      - "Functional Verification Tests"
      - "Run gitlint"
      - "Run test case"
      - "Shellcheck"
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-20.04
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
